### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by zacharlie** [kartoza/hugo-watcher#3]
I think we should rename this repository osgs-hugo-watcher and change the relevant references in the https://github.com/kartoza/OpenSource-GIS-Stack/ as having a generic version of this may be useful and would likely benefit more from this repo id

**Comment by timlinux** [comment]
So with my latest changes I have flipped your request around and set this up in a pretty generic way. We can then make a separate hugo-osgs repo for adding a starter template for OSGS users...
